apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local
  labels:
    app: dynamodb-local
spec:
  type: ClusterIP
  selector:
    app: dynamodb-local
  ports:
    - port: 8000
      targetPort: 8000
      name: http
