name: Infrastructure Management

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, destroy-tf]

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    defaults:
      run:
        working-directory: ./terraform
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ">= 1.10"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          # Write the variable content to a file
          cat > terraform.tfvars << 'EOF'
          ${{ vars.TERRAFORM_TFVARS }}
          EOF

          terraform plan -var-file=terraform.tfvars


  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./terraform
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          # Write the variable content to a file
          cat > terraform.tfvars << 'EOF'
          ${{ vars.TERRAFORM_TFVARS }}
          EOF

          terraform apply -var-file=terraform.tfvars -auto-approve


  deploy-application:
    name: 'Deploy Application to EKS'
    runs-on: ubuntu-latest
    needs: terraform-apply
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Make script executable
        run: chmod +x ./scripts/destroy-app.sh && chmod +x ./scripts/deploy-app.sh

      - name: Clean up Application
        run: ./scripts/destroy-app.sh

      - name: Deploy Application
        run: ./scripts/deploy-app.sh


  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    if: github.base_ref == 'destroy-tf' && github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Make script executable
        run: chmod +x ./scripts/destroy-app.sh

      - name: Clean up Application
        run: ./scripts/destroy-app.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./terraform
        run: |
          aws s3 rm s3://${{ vars.BUCKET_NAME }} --recursive 2>/dev/null || echo "S3 bucket is already empty or does not exist"

          # Write the variable content to a file
          cat > terraform.tfvars << 'EOF'
          ${{ vars.TERRAFORM_TFVARS }}
          EOF

          terraform destroy -auto-approve -var-file=terraform.tfvars
          